spring:
  rabbitmq:
    queue-names:
      stock-orderCreated: stock-order-created-queue
      payment-stockReserved: payment-stock-reserved-queue
      order-paymentCompleted: order-payment-completed-queue
      order-paymentFailed : order-payment-failed-queue
      stock-paymentFailed : stock-payment-failed-queue
      order-stockNotReserved: order-stock-not-reserved-queue

    exchange-names:
      saga-event-exchange: saga-event-exchange

    routing-keys:
      stock-orderCreated: stock-order-created
      payment-stockReserved: payment-stock-reserved
      order-paymentCompleted: order-payment-completed
      order-paymentFailed: order-payment-failed
      stock-paymentFailed: stock-payment-failed
      order-stockNotReserved: order-stock-not-reserved
